// import './styles/global.css';
import './styles/build.css';
export { default as Avatar } from './component/Avatar';
export { default as ChatContainer } from './component/ChatContainer';
export { default as ChatInput } from './component/ChatInput';
export { default as ConfigProvider } from './component/ConfigProvider';
export { default as EmojiPicker } from './component/EmojiPicker';
export { default as EmojiPickerDefault } from './component/EmojiPicker/Picker';
export { default as EmojiPickerPopover } from './component/EmojiPicker/Popover';
export { default as Foo } from './component/Foo';
export { default as Header } from './component/Header';
export { default as Icon } from './component/Icon';
export { default as Icons } from './component/Icons';
export { default as TextItem } from './component/TextItem';
